version: '3.4'
services:
  nginx:
    image: nginx
    ports:
      - 4000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/content:/usr/share/nginx/html

  app:
    build:
      context: ../../
    depends_on:
      - nginx
      - database-bambu-test
      - database-tenant1-test
      - database-tenant2-test
    ports:
      - 3000:3000
      
  database-bambu-test:
    image: postgres:9.6-alpine
    ports:
      - 7000:5432
    environment:
      POSTGRES_DB: USER_MANAGEMENT
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  database-tenant1-test:
    image: postgres:9.6-alpine
    ports:
      - 7001:5432
    environment:
      POSTGRES_DB: USER_MANAGEMENT
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  database-tenant2-test:
    image: postgres:9.6-alpine
    ports:
      - 7002:5432
    environment:
      POSTGRES_DB: USER_MANAGEMENT
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
